services:
  gateway:
    build: .
    env_file: .env
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 8080
      MAD_SERVICE_URL: http://host.docker.internal:4000
      HW_SERVICE_URL: http://host.docker.internal:4100
      FDS_SERVICE_URL: http://host.docker.internal:4200
      FOSS_SERVICE_URL: http://host.docker.internal:4300
      KMS_SERVICE_URL: http://host.docker.internal:4500
      WKMS_SERVICE_URL: http://host.docker.internal:4600
    ports: ['127.0.0.1:8080:8080']
    extra_hosts: ['host.docker.internal:host-gateway']
    read_only: true
    security_opt: ['no-new-privileges:true']
    cap_drop: [ALL]
    init: true
    restart: unless-stopped
